spring.application.name=microservicio-mensajeria
appDescripcion = API para enviar notificaciones
appVersion = 1.0.0

server.port=8082
#------------hosts plazoletas-----------------
microservicioUsuarios=http://localhost:8080
microserviciopropietarios=${microservicioUsuarios}/api/v1/usuarios